/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kayzio_observer_model_DLLCall */

#ifndef _Included_com_kayzio_observer_model_DLLCall
#define _Included_com_kayzio_observer_model_DLLCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIIIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIIIIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kayzio_observer_model_DLLCall
 * Method:    functionF
 * Signature: (IIIIIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_kayzio_observer_model_DLLCall_functionF__IIIIIIIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
